### ISSUE TITLE
Website Reviewer Nomination: willihay

### ISSUE THREAD

**Issue by willihay** [o3de/sig-docs-community#103]
### Nominee's GitHub username

willihay

### Relevant experience

- [Added support for Mermaid.js diagram tool](https://github.com/o3de/o3de.org/pull/2167).
- [Added website versioning](https://github.com/o3de/o3de.org/pull/2087) and [additional enhancements](https://github.com/o3de/o3de.org/pull/2117).
- [Improved website font style at H4 level](https://github.com/o3de/o3de.org/pull/840).

### Nomination Review Checklist

- [x] 3+ contributions for web content (CSS, Javascript, HTML, or Hugo layouts) successfully submitted to o3de.org.
- [x] 30+ lines of code change across all web content submissions accepted to o3de.org.
- [x] 2+ approvers from the Website Reviewers group, _or_ 2+ some combination of:
* 1 approval of SIG-Docs-Community Maintainer or Chair
* 1 approval of SIG-UI-UX (for evaluating site UX changes as part of submissions)
* 1 approval of a reviewer from a technical SIG who has experience or specialization in frontend development

**Comment by chanmosq** [comment]
I support this nomination!

**Comment by FiniteStateGit** [comment]
I support this nomination.

**Comment by chanmosq** [comment]
During meeting on 3/7/23, @aFinchy also supported this nomination. 

@willihay is now a part of the website reviewer group.
