### ISSUE TITLE
Roadmap: O3DE Docs & Community SIG Elections | 03-2023

### ISSUE THREAD

**Issue by chanmosq** [o3de/sig-docs-community#107]
### Summary
We've reached the end of a term and it's time to run elections for D&C SIG chair/co-chair. This is a standard process for running SIG business. Elections period is typically two weeks long.

**Timeline**: 
- March 7: At team meeting, announce sig elections and determine sig member to create the open election announcement. Announce open election announcement to sig-docs-community mailing list and sig-all in Discord.  
- March 20-31: Nominations period. Follow [Election Guidelines](https://github.com/o3de/community/blob/main/O3DE%20Elections/O3DE%20Elections%20Guide.md)
- April 4: Announce new SIG chair

```[tasklist]
### Tasks
- [ ] Member of the docs-community SIG (non-chair) must create the open election announcement. ([Example](https://github.com/o3de/sig-docs-community/issues/57))
- [ ] At the next sig meeting April 4, we'll review the elections and determine the next sig chairs. Voting during the meeting may occur to come to a unanimous decision. 
```

### Related Links
Link to additional information such as RFC related to the roadmap item.

---
_Learn more about [O3DE roadmaps](https://github.com/o3de/sig-release/issues/79)._

**Comment by ShaunaGordon** [comment]
This is a year and a half old, and the SIG team has completely turned over, so closing this.
