### ISSUE TITLE
SIG Elections 12/3 - 12/17 Nominations

### ISSUE THREAD

**Issue by sptramer** [o3de/sig-docs-community#24]
## SIG Docs-Community chair / co-chair elections for 2022

For the first year of O3DE, the D&C chair has been staffed as an interim position. It's time to hold some official elections, following some of the [proposed guidance](https://github.com/o3de/community/discussions/105) but with our own process due to the holiday season and in order to expedite the elections into next year.

## The chair / co-chair roles

The chair and co-chair serve equivalent roles in the governance of the SIG and are only differentiated by title in that the highest vote-getter is the chair and the second-highest is the co-chair. The chair and co-chair are expected to govern together in an effective way and split their responsibilities to make sure that the SIG operates smoothly and has the availability of a chairperson at any time.

Unless **distinctly required**, the term "chairperson" refers to either/both of the chair and co-chair. If a chair or co-chair is required to perform a specific responsibility for the SIG they will always be addressed by their official role title.

In particular, if both chairpersons would be unavailable during a period of time, **the chair is considered to be an on-call position during this period.** As the higher vote-getter they theoretically represent more of the community and should perform in that capacity under extenuating circumstances. This means that if there is an emergency requiring immediate action from the Documentation & Community SIG, the chair will be called to perform a responsibility.

### Responsibilities

* Schedule and proctor regular SIG meetings on a cadence to be determined by the SIG.
* Serve as a source of authority (and ideally wisdom) with regards to O3DE documentation. Chairpersons are the ultimate arbiters of many documentation standards, processes, and practices.
* Participate in the SIG Docs-Community Discord channel and on the GitHub Discussion forums.
* Serve as a representative of the broader O3DE community to all other SIGs, partners, the governing board, and the Linux Foundation.
* Represent the SIG to O3DE partners, the governing board, and the Linux Foundation.
* Coordinate with partners and the Linux Foundation regarding official community events.
* Represent (or select/elect representatives) to maintain relationships with all other SIGs as well as the marketing committee.
* Serve as an arbiter in SIG-related disputes.
* Coordinate releases with SIG Release.
* Assist contributors in finding resources and setting up official project or task infrastructure monitored/conducted by the SIG.
* Long-term planning and strategy for the course of documentation for O3DE.
* Maintain a release roadmap for the O3DE documentation.

**Additionally**, at this stage of the project, the SIG chairpersons are expected to act in the Maintainer role for review and merge purposes only, due to the lack of infrastructure and available reviewer/maintainer pool.

... And potentially more. Again, this is an early stage of the project and chair responsibilities have been determined more or less ad-hoc as new requirements and situations arise. In particular the **community** half of this SIG has been very lacking due to no infrastructural support, and a chairperson will ideally bring some of these skills.

## Nomination

Nomination may either be by a community member or self-nomination. A nominee may withdraw from the election at any time for any reason until the election starts on 12/3.

### Nomination requirements

For this election, nominees are required to have at minimum **two merged submissions to o3de.org** (must be accepted by 2022-01-31). This is to justify any temporary promotion to Maintainer as required by this term as chairperson. Submissions may be in-flight as of the nomination deadline (2021-12-03 12PM PT), but the nominee must meet the 2-merge requirement by the end of the election or they will be removed from the results.

Any elected chairperson who does not currently meet the Maintainer status will be required to work with contributors from the SIG to produce an appropriate number of accepted submissions by **January 31, 2022** or they will be removed and another election will be held.

The only other nomination requirement is that the nominee agrees to be able to perform their required duties and has the availability to do so, taking into account the fact that another chairperson will always be available as a point of contact.

### How to nominate

Nominate somebody (including yourself) by responding to this issue with:

* A statement that the nominee should be nominated for a chair position in the Documentation & Community SIG. Nominees are required to provide a statement that they understand the responsibilities and requirements of the role, and promise to faithfully fulfill them and follow all contributor requirements for O3DE.
* The name under which the nominee should be addressed. Nominees are allowed to contact the election proctor to have this name changed.
* The GitHub username of the nominee (self-nominations need not include this; it's on your post.)
* Nominee's Discord username (sorry, but you must be an active Discord user if you are a chairperson.)

## Election process

The election will be conducted between 2021-12-03 12:00PM PT and 2021-12-17 12:00PM PT and held through an online poll. Votes will be anonymous and anyone invested in the direction of O3DE and its documentation may vote. If you choose to vote, we ask that you be familiar with the nominees.

The current interim chair (@sptramer) will announce the results in the sig-docs-community Discord and on the sig-docs-community O3DE mailing list no later than 2021-12-17 1:00PM PT. At that time if there is a dispute over the result or concern over vote tampering, voting information will be made public to the extent that it can be exported from the polling system and the SIG will conduct an independent audit under the guidance of a higher governing body in the foundation.

The elected chairpersons will begin serving their term on 2022-01-01 at 12AM PT. Tentatively SIG D&C chairs will be elected on a **yearly basis**. If you have concerns about wanting to replace chairs earlier, please discuss in the [request for feedback on Governance](https://github.com/o3de/community/discussions/105).

**Comment by sptramer** [comment]
I would like to nominate myself (Stephen Tramer) for a chairship. I understand the responsibilities and requirements of the role, having performed them for the last year, and will continue to fulfill them and all contributor requirements for O3DE.

* Nominee name: Stephen Tramer
* Discord: stramer#7057

**Comment by FiniteStateGit** [comment]
I, Jonathan Capes, nominate myself and accept nomination for a chair position in the Docs-Community SIG, and will serve if elected.  I affirm that I understand the requirements and responsibilities of the chairpersonship.  I further affirm that I will fulfill the requirements and responsibilities of both the chairpersonship and of a O3DE contributor.

**Comment by NiklasHenricson** [comment]
> I would like to nominate myself (Stephen Tramer) for a chairship. I understand the responsibilities and requirements of the role, having performed them for the last year, and will continue to fulfill them and all contributor requirements for O3DE.
> 
> * Nominee name: Stephen Tramer
> * Discord: stramer#7057

I 2nd Stephen's nomination. He has really good knowledge of the engine, the needs for software developers, he listens to others which is one of his strongest sides. Something I haven't experienced with other candidates. I'm there fore behind his decision to step up here.

**Comment by sptramer** [comment]
Nominations have concluded. In light of the fact that there are only two nominees and one received a "second", as well as unanimous agreement among the chairpersons, **Stephen Tramer (@sptramer)** will serve as Chair and **Jonathan Capes (@FiniteStateGit)** will serve as Co-chair.

Congratulations!
