### ISSUE TITLE
Proposed SIG-Docs meeting agenda for February-08-2022

### ISSUE THREAD

**Issue by FiniteStateGit** [o3de/sig-docs-community#25]
## Meeting Details

* **Date/Time:** February 8, 2022 @ 11:00am PST / 7:00pm UTC
* **Location:** [Discord SIG-Docs Voice Room](https://discord.gg/p3padwr58u)
* **Moderator:** SIG-Docs chair
* **Note Taker:** TBD

The [SIG-Docs Meetings](https://github.com/o3de/sig-docs-community/blob/main/meetings/README.md) contains the history past calls, including a link to the agenda, recording, notes, and resources.

## SIG Updates

* Regular SIG-Docs meeting scheduled for the second Tuesday of every month at 11am PST / 7pm UTC.

## Initial Agenda

The pre-approved agenda for this meeting is as follows:

* **Sig Updates** - **Stephen Tramer** - **10m**
  * Two releases! (2111.1 and 2111.2)
  * Chair elections! @sptramer and @FiniteStateGit are the chairs of sig-docs-community.
  * Staffed community manager for our "and community": Amy Finch (Finchy, @aFinchy)
  * 2022 planning season: Propose projects, write RFCs, and help build our roadmap for the first part of 2022.
* Reviewer/Maintainer promotions - **Stephen Tramer** - **5m**
  * https://github.com/o3de/sig-docs-community/issues/28
  * https://github.com/o3de/sig-docs-community/issues/27
  * https://github.com/o3de/sig-docs-community/issues/26
  * https://github.com/o3de/sig-docs-community/issues/30
* Project proposals and updates - **Stephen Tramer** - **10m**:
  * [Active projects](./projects.md)
  * https://github.com/o3de/sig-docs-community/pull/31

The remaining time of this meeting is for community agenda items. Please remember to propose and vote!

## Suggesting and voting on agenda items

Our community is welcome to suggest and vote on agenda items. If you suggest an item you need to have a designated presenter (normally the issue filer), but any community member can vote and isn't required to attend meetings or even participate in further discussion. If you think something is a good idea to discuss for the O3DE community, please upvote!

:+1: reactions to proposed agenda items are counted as YEA votes for taking up discussion, and :-1: as NAY. Votes on items don't determine the final agenda, but do influence it and are strongly taken into consideration as a representation of what the O3DE community wants to see from the project.

### Agenda item format

If you leave a comment on this issue to propose an agenda item, please use the following format:

```
**Topic**: The topic you'll be presenting on
**Presenter**: Who will present (may be a team name or TBD)
**Length of time**: Estimate the amount of time you believe discussion will take. This should not be more than 15 minutes without SIG approval.

Include a description of your topic. Make sure to link to any supplementary materials such as RFCs, forum discussions, issues, etc.
```

Remember to add the :+1: and :-1: reactions manually, so they appear and are obvious to voters!

**Comment by hultonha** [comment]
**Topic**: As an O3DE contributor I would like to be able to submit documentation of features that are in o3de development branch without affecting the release documentation of o3de.
**Presenter**: @hultonha (also potentially @moraaar)
**Length of time**: 10 minutes

Tagging @amznestebanpapp for visibility on this as they have expressed interest in it too.

**Comment by sptramer** [comment]
**Topic**: SIG role in tooltips, in-editor help, etc etc
**Presenter**: @sptramer 
**Length of time**: 10-15m

The docs sig occasionally gets requests to review in-editor help information, and most importantly, our role in in-editor help has come up across the PRs https://github.com/o3de/o3de.org/pull/1339 and https://github.com/o3de/o3de/pull/6555. Engineers may be unwarily making changes which impact the user experience of documentation, and we should consider the sig-docs-community role in making sure that in-Editor documentation resources (whether static strings, site links, or something else) are appropriately reviewed and updated.

**Comment by Ulrick28** [comment]
**Topic**: How much lead time does sig-docs require before a release?
**Presenter**: @AMZN-JoeB
**Length of time**: 5m

We are putting together the time cost/overhead of a release to help determine a realistic release cadence for O3DE. sig-release would like to know how much lead time sig-docs needs to prepare for a release.
