### ISSUE TITLE
SIG Reviewer/Maintainer Nomination: @chanmosq

### ISSUE THREAD

**Issue by sptramer** [o3de/sig-docs-community#26]
#### Documentation maintainer

* [x] Has been a Reviewer for 2+ months
* [x] 8+ reviewed Pull Requests in the previous 2 months
* [x] 2+ D&C SIG Maintainers who support promotion.

**Maintaining status:** 8+ Pull Requests reviewed per month.

-------
##### Fill out the template below including nominee GitHub user name, desired role and personal GitHub profile
-------------------

I would like to nominate @chanmosq to become a ***Maintainer*** on behalf of ***sig-docs-community***. I verify that they have fulfilled the prerequisites for this role.

**NOTE:** @chanmosq has been unofficially performing the role of Reviewer for 6+ months, since O3DE launch.

* Nominee's GitHub Profile: @chanmosq 

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by micronAMZN** [comment]
I support the nomination of @chanmosq to reviewer/maintainer of the sig-docs-community.

**Comment by sptramer** [comment]
Approved!
