### ISSUE TITLE
SIG Reviewer/Maintainer Nomination: @micronAMZN

### ISSUE THREAD

**Issue by sptramer** [o3de/sig-docs-community#27]
#### Documentation maintainer

* [x] Has been a Reviewer for 2+ months
* [x] 8+ reviewed Pull Requests in the previous 2 months
* [x] 2+ D&C SIG Maintainers who support promotion.

**Maintaining status:** 8+ Pull Requests reviewed per month.

-------
##### Fill out the template below including nominee GitHub user name, desired role and personal GitHub profile
-------------------

I would like to nominate: @micronAMZN to become a ***Maintainer*** on behalf of ***sig-docs-community***. I verify that they have fulfilled the prerequisites for this role.

*NOTE:* Mike has been unofficially performing in the role of reviewer for 6+ months since the launch of O3DE.

* Nominee's GitHub Profile: @micronAMZN 

*Reviewers & Maintainers that support this nomination should comment in this issue.*

**Comment by FiniteStateGit** [comment]
I support @micronAMZN's promotion to maintainer of sig-docs-community.

**Comment by chanmosq** [comment]
I support the nomination of @micronAMZN to maintainer of the sig-docs-community.

**Comment by sptramer** [comment]
Approved!
