### ISSUE TITLE
Proposed RFC: Separate `main` and `development` branches for versioning

### ISSUE THREAD

**Issue by sptramer** [o3de/sig-docs-community#32]
## Separating `main` and `development` website branches

During the [2022-02-08 SIG meeting](https://github.com/o3de/sig-docs-community/issues/25) we discussed two ongoing issues: Website versioning (represented as an [official SIG project](https://github.com/o3de/sig-docs-community/blob/main/projects.md)) and the need to _currently_ keep in-flight documentation for "next release" off of the website, while also accessible to users. There have been some stop-gap efforts such as using the [o3de wiki](https://github.com/o3de/o3de/wiki), which fragments our documentation.

This proposal is to prepare for full website versioning by effectively beginning a separation between "last binary release" (`main`) and "in-flight work" (`development`). While there are issues with how features are selected for release, patch backporting, etc. we expect these problems to be discussed as part of the full website versioning proposal. This is an initial stage to enable minimal separation of the two workflows and enable our future versioning.

### What is the relevance of this feature?

There are two primary issues which prompted the proposal for separating `development` and `main`:

* Users may get unreliable information, as we expect at this point many of them will be using at minimum the 2111.2 QoL update, and in-flight feature documentation is not representative of this release - even if there are only minor adjustments to existing features, if they are updated for dev, any user running a binary (or built from git branch) release will likely encounter issues. Keeping `main` (and the live site) locked to "latest release" until a full versioning strategy is in place will be helpful to users.
* Developers have difficulty getting work for in-flight features merged to `main`. This is because of the high standard of quality that we try to maintain on live documentation, especially for _new_ documentation. We want to encourage engineer contributions as the subject matter experts on reference and in-depth feature knowledge, and a higher-velocity, lower-stabilization `development` branch enables this.

### What are the advantages of the feature?

* **Separation of in-flight from released features**, as described above.
  * Better user experience (documentation is "locked to release")
  * Better developer experience (developers have a lower bar of acceptance for in-flight feature docs; They aren't required to worry about "sitting on" docs until code is ready for a versioned release; They will be able to accept longer turn-around times in edit; It will be clearer where "bug fix" docs vs. "new feature" docs go)
* **Preparation for versioning strategy**: A versioning strategy will include a plan for documenting `o3de/development`, which may be a different workflow than proposed in this RFC; However, it's expected that any versioning strategy will work off of git tags, branches, or another mechanism that enables easy versioning automation. The branch separation strategy also prepares our audience for the migration to a versioned website and will theoretically make the versioning even easier.

### What are the disadvantages of the feature?

* **Representation of velocity.** In the design description the practical infrastructure concerns lay this out, but until there is inline versioning on the website for docs in some capacity, we will want to stage `main` and `development` separately. This will put `development` on a subdomain, such as `dev.o3de.org` - separating visibility into in-flight features from released features. *This is intentional and by design, as outlined in the proposal.* The philosophical argument is that user experience on docs matters, and unless we have actionable telemetry, we must make assumptions on whether users are operating off `development` or a versioned release. Activity in Discord and on forums at this time is anecdata that many users are sticking with versioned releases.
  * **MITIGATION:** Actively directing users reading versioned documentation (`main`, o3de.org) to dev docs (`development`, dev.o3de.org) and vice-versa, at minimum on the `/docs` landing page index (and presumably the indexes of each major guide.)
* **Confusion in migration to full versioning.** Full versioning of the website will require UI/UX integrations and potentially additional build infrastructure, and should not rely on subdomains. This proposal is for a _stopgap measure_ to address what we see as an urgent need, as there is no current timeline for the implementation of website versioning. As a consequence, the technical design is as minimalist as possible.
  * **MITIGATION:** This is why `301 PERMANENTLY MOVED` exists as an HTTP response status code. `dev.o3de.org` will redirect to the appropriate versioned documentation for `development` when full versioning is in place.

#### GitHub o3de.org changes

* The creation of a `development` branch. The current state of `main` will be considered to be representative of 2111.2, although it has been updated with new features since that release.

#### Netlify changes

* We would be publishing both `main` (as our production site) and `development` (as dev.o3de.org). See the [Netlify branch publishing documentation](https://docs.netlify.com/site-deploys/overview/#branches-and-deploys). There is infrastructure support for supporting this feature.

#### Global search indexing

* We should **determine** if site indexing should be disabled for `dev.o3de.org`, at the risk of making in-flight feature docs less discoverable. Keeping it enabled will pollute search results however, and likely lead to the same problem we experience now (users seeing bad information.)

#### Documentation changes

* Contributor guides will need to clarify the purposes of `main` and `development` on documentation. This **includes** code contributors, as they are meant to be the primary submitters to `development`.
* Signposting on `dev.o3de.org` indicating that the user is on the "development branch site" documenting the current code base, in the form of a site banner or other visible UI.
* Signposting on _specific_ o3de.org landing pages pointing users to the development site.

### Technical considerations

Outlined above regarding implementation.

### Are there any alternatives to this feature?

* Full rollout of a versioned website, date TBD.
* Separating `development` and `2111.2` into separate subdirectories on the site, but with no easy UX to navigate between them.

### Are there any open questions?

* Is `dev.o3de.org` an appropriate name?
* Should we wait for full versioning?
* Is this model going to be easy to migrate to a versioning system?
* Should robots be prevented from indexing `dev.o3de.org`?
* Which pages on o3de.org should have signposting for how to get to the development branch documentation?

**Comment by hultonha** [comment]
I'm fully supportive of this RFC, sounds like a great idea. Thanks for putting this together so quickly @sptramer! 😄

**Comment by moraaar** [comment]
I fully support this RFC as well. This RFC delivers even more than requested, with the ability to actually have a published version of development documentation in `dev.o3de.org`. Initially I was expecting that developers could download and see locally the development documentation, but having it online in a subdomain sounds fantastic.

**Comment by lmbr-pip** [comment]
I would prefer we version docs on releases. ie snapshot docs and mark as the docs for 2011RTE etc. The o3de.org should be latest docs that track against development IMHO.

We still have a high velocity of changes and are struggling to get docs into any state.  I want to ensure we are not constructing any new barriers/confusion about how to submit docs as features come in.

I also feel we will have to spend considerable effort get dev docs up to "release" quality under this initiative. I have concerns that we are not scaled, and SIGs will be asked to give up considerable time to "polish" dev to release.

I may be missing the use case for "currently keep in-flight documentation for "next release" off of the website, while also accessible to users. ". 

What data do we have about where folks are consuming O3DE from? As an active developer I am biased towards development because thats where I work. Am happy to be shown data that the majority of users work from releases and so documentation should align with the primary way O3DE users are working with O3DE.

**Comment by sptramer** [comment]
> I would prefer we version docs on releases. ie snapshot docs and mark as the docs for 2011RTE etc. o3de.org should be latest docs that track against development IMHO. This introduces very little change in current process.

This is tracked as an [official SIG project](https://github.com/o3de/sig-docs-community/blob/main/projects.md) and there is a forthcoming RFC for a full versioning model. This is a stopgap RFC which is meant to address an immediate problem ("unstable docs between releases and high-velocity dev") without considering LTS. I would like @willihay to weigh in on this one briefly since he's doing the project work.

> I would challenge to provide alternatives you have considered in this RFC.

This needs to be much more clearly articulated in the RFC, but we are limited by our usage of an OTS system which is owned as a platform and some restrictions that were discovered or advised by @willihay during his research for the upcoming RFC on general versioning. I can supplement the information on this RFC at a future date.

> I also feel we will have to spend considerable effort get dev docs up to "release" quality under this initiative. I have concerns that we are not scaled for this, and SIGs will be asked to give up considerable time to "polish" docs when we need to migrate dev to mainline.

This is a legitimate concern, and a SIG policy regarding "documentation quality" isn't yet in place to set a standard bar between  in any meaningful way, let alone between a `dev` and `main` state. Stale/unedited content will unquestionably be a problem for us in any model, but you're correct, this could make it worse and needs to be addressed.

> So what data do we have about where folks are consuming O3DE from? As an active developer I am biased towards development because thats where I work. Am happy to be shown data that the majority of users work from releases and so documentation should align with the primary way O3DE users are working with O3DE.

Currently, data about our userbase is driven by Discord, and the comments we see there are predominantly from users working with a box release rather than `development`, for better or for worse. It is an open question how splitting the docs here affects our "average user" at this stage, as called out in the RFC. I'd like some more advisement on this from @o3de/sig-release-maintainers and will have more concrete data by March.

**Comment by willihay** [comment]
>> I would prefer we version docs on releases. ie snapshot docs and mark as the docs for 2011RTE etc. o3de.org should be latest docs that track against development IMHO. This introduces very little change in current process.

> This is tracked as an [official SIG project](https://github.com/o3de/sig-docs-community/blob/main/projects.md) and there is a forthcoming RFC for a full versioning model. This is a stopgap RFC which is meant to address an immediate problem ("unstable docs between releases and high-velocity dev") without considering LTS. I would like @willihay to weigh in on this one briefly since he's doing the project work.

From my research into the doc versioning problem space, I would categorize the consumers of the o3de.org docs into two major groups:

1. Cutting edge users who work off the development branch and are not afraid to pull the latest updates at any time.
2. Users who have installed a released version of O3DE from the Installer, or built the source from a tagged release.

Clearly the first group would benefit from - and often want (or at least understand and tolerate) - cutting edge updates to docs that reflect impactful and even breaking changes in the development branch. And our code contributors would certainly benefit from having a place to immediately make those doc changes.

However, these same cutting edge changes to the docs would periodically confuse the second group, serving them with incorrect or incomplete information. I feel that this sort of potential for confusion should not be part of the _default_ doc experience (i.e. o3de.org). We already have enough problems with gaps and outdated information in this default set. ;-)

I'd like to also note that in the official SIG project that @sptramer mentioned, I will be proposing that the longer term website versioning include a doc version selector mechanism to easily switch between doc versions, and will likely use a browser cookie to remember the reader's choice. This should help readers self-select a doc set that fits their needs.

**Comment by sptramer** [comment]
**Additional note:** There's nothing that prevents us from pre-staging and splitting `main` and `development` at this point, with the understanding that `main` is the only published branch. If this will help with resolving this conflict in a more urgent way, we can add that before RFC approval with the understanding that this RFC may be rejected in favor of a forthcoming full versioning RFC.

**Comment by hultonha** [comment]
> **Additional note:** There's nothing that prevents us from pre-staging and splitting `main` and `development` at this point, with the understanding that `main` is the only published branch. If this will help with resolving this conflict in a more urgent way, we can add that before RFC approval with the understanding that this RFC may be rejected in favor of a forthcoming full versioning RFC.

I'd be in favor of this if it makes it easier for teams to start adding documentation earlier! 🙂

**Comment by sptramer** [comment]
**ACCEPTED:** RFC split of `main`/`development`
**ACCEPTED:** Publishing of `development` to:
  * Publish to default Netlify staging `development--staging.o3deorg.netlify.app`
  * Request no-indexing `robots.txt` on development
  * Provide version numbers / identifiers in headers for all docs sites from this point on
  * Still need to fully identify a release strategy for merging `development -> main`

**Comment by sptramer** [comment]
Closed as accepted
