### ISSUE TITLE
Proposed SIG-Docs-Community Feature Grid

### ISSUE THREAD

**Issue by FiniteStateGit** [o3de/sig-docs-community#40]
Features(modules) are organized by workflow (in H3); they include the concepts, tools, and components associated with the workflow.  Features are scored on four metrics: the completeness of conceptual material, tutorial content, sample content, and the API documentation for reflected features.  Metrics that are not scored for a feature are labeled 'N/A'.  A documentation link to conceptual material is listed in the last column.  In some cases, I could not identify a primary location to link to a feature with partial coverage. 

### Onboarding

| Module | Conceptual Material | Tutorial Content | Sample Content | API Documentation | Documentation Link |
| :-- | :--- | :--- | :--- | :--- | :--- |
| Onboarding | :green_circle: Complete | :yellow_circle: Partial | :o: N/A | :o: N/A | https://www.o3de.org/docs/welcome-guide/ |
| Engine Config and Build | :green_circle: Complete | :yellow_circle: Partial | :o: N/A | :o: N/A | https://www.o3de.org/docs/user-guide/build/ |
| Build Platform - Windows | :green_circle: Complete | :yellow_circle: Partial | :o: N/A | :o: N/A | https://www.o3de.org/docs/welcome-guide/setup/installing-windows/ |
| Build Platform - Linux | :green_circle: Complete | :yellow_circle: Partial | :o: N/A | :o: N/A | https://www.o3de.org/docs/welcome-guide/setup/installing-linux/ |
| Build Platform - Android | :green_circle: Complete | :yellow_circle: Partial | :o: N/A | :o: N/A | https://www.o3de.org/docs/user-guide/platforms/android/generating_android_project_windows/ |
| Build Platform - MacOS | :red_circle: None | :red_circle: None | :o: N/A | :o: N/A |  |
| Project Config and Build | :green_circle: Complete | :yellow_circle: Partial | :o: N/A | :o: N/A | https://www.o3de.org/docs/user-guide/project-config/ |
| Gem System | :yellow_circle: Partial | :yellow_circle: Partial | :o: N/A | :o: N/A | https://www.o3de.org/docs/user-guide/programming/gems/ |
| Gem Catalog | :green_circle: Complete | :yellow_circle: Partial | :o: N/A | :o: N/A | https://www.o3de.org/docs/user-guide/project-config/add-remove-gems/ |
| Editor | :green_circle: Complete | :yellow_circle: Partial | :o: N/A | :red_circle: None | https://www.o3de.org/docs/user-guide/editor/ |
| System Components | :red_circle: None | :yellow_circle: Partial | :o: N/A | :red_circle: None |  |
| Viewport | :green_circle: Complete | :yellow_circle: Partial | :o: N/A | :o: N/A | https://www.o3de.org/docs/user-guide/editor/viewport/ |
| Entity Outliner | :yellow_circle: Partial | :yellow_circle: Partial | :o: N/A | :o: N/A | https://www.o3de.org/docs/user-guide/editor/entity-outliner/ |
| Entity Inspector | :yellow_circle: Partial | :yellow_circle: Partial | :o: N/A | :o: N/A | https://www.o3de.org/docs/user-guide/editor/entity-inspector/ |
| Console | :green_circle: Complete | :yellow_circle: Partial | :o: N/A | :yellow_circle: Partial | https://www.o3de.org/docs/user-guide/editor/console/ |
| Asset Browser | :red_circle: None | :yellow_circle: Partial | :o: N/A | :o: N/A |  |
| Asset Editor | :red_circle: None | :yellow_circle: Partial | :o: N/A | :o: N/A |  |
| Project Manager | :green_circle: Complete | :yellow_circle: Partial | :o: N/A | :o: N/A | https://www.o3de.org/docs/user-guide/project-config/project-manager/ |
| CLI | :green_circle: Complete | :yellow_circle: Partial | :o: N/A | :green_circle: Complete | https://www.o3de.org/docs/user-guide/project-config/cli-reference/ |

### Experience design

| Module | Conceptual Material | Tutorial Content | Sample Content | API Documentation | Documentation Link |
| :-- | :--- | :--- | :--- | :--- | :--- |
| Entities | :yellow_circle: Partial | :yellow_circle: Partial | :red_circle: None | :red_circle: None |  |
| Levels | :red_circle: None | :yellow_circle: Partial | :red_circle: None | :red_circle: None |  |
| Prefabs | :red_circle: None | :yellow_circle: Partial | :red_circle: None | :red_circle: None |  |
| Physics | :yellow_circle: Partial | :yellow_circle: Partial | :red_circle: None | :red_circle: None | https://www.o3de.org/docs/user-guide/interactivity/physics/ |
| Event Buses | :yellow_circle: Partial | :red_circle: None | :red_circle: None | :yellow_circle: Partial | https://www.o3de.org/docs/user-guide/programming/ebus/ |
| AZ Events | :red_circle: None | :red_circle: None | :red_circle: None | :red_circle: None |  |
| Scripting | :green_circle: Complete | :yellow_circle: Partial | :red_circle: None | :o: N/A | https://www.o3de.org/docs/user-guide/scripting/ |
| Audio | :green_circle: Complete | :red_circle: None | :red_circle: None | :o: N/A | https://www.o3de.org/docs/user-guide/interactivity/audio/ |
| AI | :red_circle: None | :red_circle: None | :red_circle: None | :o: N/A |  |
| Input | :yellow_circle: Partial | :yellow_circle: Partial | :red_circle: None | :o: N/A | https://www.o3de.org/docs/user-guide/interactivity/input/ |
| Cameras | :red_circle: None | :red_circle: None | :red_circle: None | :o: N/A |  |
| UI | :green_circle: Complete | :yellow_circle: Partial | :red_circle: None | :o: N/A | https://www.o3de.org/docs/user-guide/interactivity/user-interface/ |
| Audio Components | :green_circle: Complete | :red_circle: None | :red_circle: None | :yellow_circle: Partial | - |
| Camera Components | :green_circle: Complete | :red_circle: None | :red_circle: None | :green_circle: Complete | - |
| Gameplay Components | :green_circle: Complete | :yellow_circle: Partial | :red_circle: None | :green_circle: Complete | - |
| PhysX Components | :green_circle: Complete | :yellow_circle: Partial | :red_circle: None | :red_circle: None | - |
| Scripting Components | :yellow_circle: Partial | :yellow_circle: Partial | :red_circle: None | :yellow_circle: Partial | - |
| Shape Components | :green_circle: Complete | :red_circle: None | :red_circle: None | :green_circle: Complete | https://www.o3de.org/docs/user-guide/components/reference/shape/ |
| Transform Component | :green_circle: Complete | :yellow_circle: Partial | :red_circle: None | :yellow_circle: Partial | - |
| Non-uniform Scale Component | :green_circle: Complete | :red_circle: None | :red_circle: None | :yellow_circle: Partial | - |
| Input Components | :yellow_circle: Partial | :yellow_circle: Partial | :red_circle: None | :yellow_circle: Partial | - |
| UI Components | :yellow_circle: Partial | :yellow_circle: Partial | :red_circle: None | :red_circle: None | - |
| UI Canvas Components | :green_circle: Complete | :yellow_circle: Partial | :red_circle: None | :red_circle: None | https://www.o3de.org/docs/user-guide/interactivity/user-interface/components/ |
| UI Editor | :green_circle: Complete | :yellow_circle: Partial | :red_circle: None | :o: N/A | https://www.o3de.org/docs/user-guide/interactivity/user-interface/editor/ |
| Script Canvas | :green_circle: Complete | :yellow_circle: Partial | :red_circle: None | :o: N/A | https://www.o3de.org/docs/user-guide/scripting/script-canvas/ |
| Lua Editor | :green_circle: Complete | :yellow_circle: Partial | :red_circle: None | :o: N/A | https://www.o3de.org/docs/user-guide/scripting/lua/lua-editor/ |
| PhysX Configuration | :green_circle: Complete | :yellow_circle: Partial | :red_circle: None | :red_circle: None | https://www.o3de.org/docs/user-guide/interactivity/physics/nvidia-physx/configuring/ |

### Actor development

| Module | Conceptual Material | Tutorial Content | Sample Content | API Documentation | Documentation Link |
| :-- | :--- | :--- | :--- | :--- | :--- |
| Actors | :yellow_circle: Partial | :yellow_circle: Partial | :red_circle: None | :o: N/A | https://www.o3de.org/docs/user-guide/components/reference/animation/actor-component-entity-setup/ |
| Animation | :green_circle: Complete | :yellow_circle: Partial | :red_circle: None | :o: N/A | https://www.o3de.org/docs/user-guide/visualization/animation/char-intro/ |
| Animation Components | :green_circle: Complete | :yellow_circle: Partial | :red_circle: None | :yellow_circle: Partial | - |
| PhysX Components | :yellow_circle: Partial | :yellow_circle: Partial | :red_circle: None | :red_circle: None | - |
| Animation Editor | :green_circle: Complete | :yellow_circle: Partial | :red_circle: None | :o: N/A | https://www.o3de.org/docs/user-guide/visualization/animation/ |

### World building

| Module | Conceptual Material | Tutorial Content | Sample Content | API Documentation | Documentation Link |
| :-- | :--- | :--- | :--- | :--- | :--- |
| Terrain | :red_circle: None | :yellow_circle: Partial | :red_circle: None | :o: N/A |  |
| Vegetation | :green_circle: Complete | :yellow_circle: Partial | :red_circle: None | :o: N/A | https://www.o3de.org/docs/user-guide/gems/reference/environment/vegetation/ |
| Gradient Components | :yellow_circle: Partial | :yellow_circle: Partial | :red_circle: None | :green_circle: Complete |  |
| Surface Data Components | :yellow_circle: Partial | :red_circle: None | :red_circle: None | :o: N/A |  |
| Terrain Components | :yellow_circle: Partial | :yellow_circle: Partial | :red_circle: None | :green_circle: Complete |  |
| Vegetation Components | :green_circle: Complete | :yellow_circle: Partial | :red_circle: None | :green_circle: Complete | https://www.o3de.org/docs/user-guide/gems/reference/environment/vegetation/ |
| Landscape Canvas | :red_circle: None | :red_circle: None | :red_circle: None | :o: N/A |  |

### Look development

| Module | Conceptual Material | Tutorial Content | Sample Content | API Documentation | Documentation Link |
| :-- | :--- | :--- | :--- | :--- | :--- |
| Assets | :yellow_circle: Partial | :yellow_circle: Partial | :red_circle: None | :o: N/A | https://www.o3de.org/docs/user-guide/assets/ |
| Materials | :green_circle: Complete | :yellow_circle: Partial | :red_circle: None | :o: N/A | https://www.o3de.org/docs/atom-guide/look-dev/materials/ |
| Shaders | :yellow_circle: Partial | :red_circle: None | :red_circle: None | :o: N/A | https://www.o3de.org/docs/atom-guide/look-dev/shaders/ |
| Atom Renderer | :green_circle: Complete | :yellow_circle: Partial | :green_circle: Complete | :o: N/A | https://www.o3de.org/docs/atom-guide/ |
| Cinematics | :green_circle: Complete | :yellow_circle: Partial | :red_circle: None | :o: N/A | https://www.o3de.org/docs/user-guide/visualization/cinematics/ |
| Asset Processor | :green_circle: Complete | :yellow_circle: Partial | :red_circle: None | :o: N/A | https://www.o3de.org/docs/user-guide/assets/asset-processor/ |
| Asset Pipeline | :green_circle: Complete | :yellow_circle: Partial | :red_circle: None | :o: N/A | https://www.o3de.org/docs/user-guide/assets/pipeline/ |
| Python Asset Builder | :green_circle: Complete | :yellow_circle: Partial | :red_circle: None | :o: N/A | https://www.o3de.org/docs/user-guide/assets/builder/ |
| Atom Components | :yellow_circle: Partial | :yellow_circle: Partial | :red_circle: None | :yellow_circle: Partial |  |
| Material Editor | :green_circle: Complete | :yellow_circle: Partial | :red_circle: None | :o: N/A | https://www.o3de.org/docs/atom-guide/look-dev/materials/material-editor/ |
| Track View Editor | :green_circle: Complete | :yellow_circle: Partial | :red_circle: None | :o: N/A | https://www.o3de.org/docs/user-guide/visualization/cinematics/track-view/ |

### Multiplayer

| Module | Conceptual Material | Tutorial Content | Sample Content | API Documentation | Documentation Link |
| :-- | :--- | :--- | :--- | :--- | :--- |
| Multiplayer | :green_circle: Complete | :yellow_circle: Partial | :yellow_circle: Partial | :red_circle: None | https://www.o3de.org/docs/user-guide/gems/reference/multiplayer/ |
| Networking Components | :green_circle: Complete | :yellow_circle: Partial | :yellow_circle: Partial | :red_circle: None | https://www.o3de.org/docs/user-guide/networking/ |
| Cloud Components | :green_circle: Complete | :red_circle: None | :red_circle: None | :red_circle: None | https://www.o3de.org/docs/user-guide/gems/reference/aws/ |

### Project development and team collaboration

| Module | Conceptual Material | Tutorial Content | Sample Content | API Documentation | Documentation Link |
| :-- | :--- | :--- | :--- | :--- | :--- |
| Source Control | :red_circle: None | :red_circle: None | :red_circle: None | :o: N/A |  |
| Platform Development | :yellow_circle: Partial | :red_circle: None | :red_circle: None | :o: N/A | https://www.o3de.org/docs/user-guide/platforms/ |
| Platform Development - Windows | :yellow_circle: Partial | :red_circle: None | :red_circle: None | :o: N/A | https://www.o3de.org/docs/user-guide/platforms/windows/ |
| Platform Development - Linux | :yellow_circle: Partial | :red_circle: None | :red_circle: None | :o: N/A | https://www.o3de.org/docs/user-guide/platforms/linux/ |
| Platform Development - Android | :yellow_circle: Partial | :red_circle: None | :red_circle: None | :o: N/A | https://www.o3de.org/docs/user-guide/platforms/android/ |
| Platform Development - MacOS | :red_circle: None | :red_circle: None | :red_circle: None | :o: N/A |  |
| Programming | :green_circle: Complete | :green_circle: Complete | :red_circle: None | :o: N/A | https://www.o3de.org/docs/user-guide/programming/ |
| Testing | :green_circle: Complete | :green_circle: Complete | :red_circle: None | :o: N/A | https://www.o3de.org/docs/user-guide/testing/ |
| Graph Canvas | :red_circle: None | :red_circle: None | :red_circle: None | :o: N/A |  |

### Editor extension

| Module | Conceptual Material | Tutorial Content | Sample Content | API Documentation | Documentation Link |
| :-- | :--- | :--- | :--- | :--- | :--- |
| Component Development | :green_circle: Complete | :yellow_circle: Partial | :yellow_circle: Partial | :o: N/A | https://www.o3de.org/docs/user-guide/programming/components/ |
| Tools UI | :green_circle: Complete | :yellow_circle: Partial | :yellow_circle: Partial | :o: N/A | https://www.o3de.org/docs/tools-ui/ |

### Packaging and deployment

| Module | Conceptual Material | Tutorial Content | Sample Content | API Documentation | Documentation Link |
| :-- | :--- | :--- | :--- | :--- | :--- |
| Asset Bundling | :green_circle: Complete | :green_circle: Complete | :o: N/A | :o: N/A | https://www.o3de.org/docs/user-guide/packaging/asset-bundler/ |
| Release Build | :yellow_circle: Partial | :yellow_circle: Partial | :o: N/A | :o: N/A | https://www.o3de.org/docs/user-guide/packaging/overview/ |
| Release Platform - Windows | :green_circle: Complete | :green_circle: Complete | :o: N/A | :o: N/A | https://www.o3de.org/docs/user-guide/packaging/windows-release-builds/ |
| Release Platform - Linux | :red_circle: None | :red_circle: None | :o: N/A | :o: N/A |  |
| Release Platform - Android | :red_circle: None | :red_circle: None | :o: N/A | :o: N/A |  |
| Release Platform - MacOS | :red_circle: None | :red_circle: None | :o: N/A | :o: N/A |  |

**Comment by willihay** [comment]
Assuming this is a companion or addition to the product feature grid in the upcoming 22.05 release notes?

How did you determine the completeness score for the conceptual and tutorial content? What does "Complete" mean for docs? I think we should wait to release this until the Amazon docs team has had a chance to provide input from its audit, which is currently ongoing. I have a feeling there will be a lot less "Complete" scores than currently shown here. ;-)

We should only list modules that are included with O3DE. Kythera AI is not one of them.

Regarding the general format, please put the score first, followed by the description. Sorry for the extra work this will cause, but this will allow the scores to line up neatly and really aid the ability for readers to rapidly scan the table. See the [preview](https://deploy-preview-1607--o3deorg.netlify.app/docs/release-notes/archive/22-05-0/feature-state/) of the product feature grid as an example, sizing your window to fit the table contents.

**Comment by FiniteStateGit** [comment]
> Assuming this is a companion or addition to the product feature grid in the upcoming 22.05 release notes?

Yes, this is the feature grid for documentation.  Stephan and I settled on the workflows, modules, and columns to include last week.  I think we both agreed that the format should be improved for future versions; I had concerns that this had to largely align with the format of other feature grids.  

> How did you determine the completeness score for the conceptual and tutorial content? What does "Complete" mean for docs? I think we should wait to release this until the Amazon docs team has had a chance to provide input from its audit, which is currently ongoing. I have a feeling there will be a lot less "Complete" scores than currently shown here. ;-)

For conceptual content, if I couldn't identify that material was missing from the topic, it received a 'complete' score.  For tutorial content, I considered all procedural material in addition to topics in the Tutorial section.  I was expecting/hoping for many corrections to individual scores, I know the current ones are overly optimistic.

I will remove Kythera.  I can shuffle the score and description around no problem (and change which descriptions we use), generating the feature grid is automated!

**Comment by sptramer** [comment]
Notes from 5/17 meeting:

* Maybe change from a separate feature grid to just a 4-col extension on top of the existing O3DE feature grid?
* "Conceptual content": Feature descriptions (Minimum viable content), and cross-component/larger-engine tie-together
* Which is more useful:
  * Classifying by workflow feels problematic; Might be useful for prioritization and understanding of product health but not appropriate for feature grid
  * Developers look at specific feature support like "Animation motion matching" - not just the overall state of "Animation"
  * Not every feature needs every type of documentation (i.e. Installer doesn't need component docs, and viewport interaction doesn't necessary need "samples")
  * Lots of SIGs are not accurately tracking their own content needs on the feature grid, with regards to either 3D assets or sample code/projects (we help with the latter, TBD SIG helps with the former)
* How do we score, and when can we give a score of "Complete" to any feature row?
  * Maybe grade on the content quality bar? i.e. "None", "Minimum", "Partial", "Good", "Excellent" gradation? This avoids the unpleasant implications of "complete" as well
  * But "Complete" does make sense for things like reference documentation: Lua, Script Canvas, Components, API ref, etc.
* How do we track platform-specific support?
  * Release, install, platform-specific capabilities
  * Platform-related best practices for areas such as assets, networking design, etc.
* Should other SIG-docs items have a place on the feature grid? Outside of reporting docs on product, what else does the SIG need to report on?
  * i.e. Projects, initiatives, ongoing RFC acceptance, templating, contributing
  * Some of this is reporting to be handled through LFX dashboard (metrics)
  * Publishing and health of standards and practices (such as contributor guide, audience calibration, style guide, levels of content, etc.)
  * Core gem coverage - possible additional area of RYG, for overall health of a single Gem, rather than by featureset.
* Engineers want to use the term "included gems" or "bundled gems" - this helps distinguish from the engine core, and also the "core set of gems" required for every project
  * Feels like also a TSC/Marketing terminology thing?
  * Users should be able to make trust decisions on their own without an explicit "blue check" endorsement from O3DE or the O3DF - this is also a differentiator between "included" (more trusted)/"external" (trust if you want)
  * Avoid the "third party" terminology in general (feature grid and otherwise)
* Enumerate the _type_ of tutorial content available: Written, interactive, cookbook/recipe, sample code, sample project, howto
  * Could explode into "sub-grids" on top of each content type category - how do we avoid adding dimensions to the feature matrix and track appropriately without an information overload?
    * Maybe this is a feature request to the sig grid tool, where we enter EXTRA information that can be used to generate 2 charts: A SIG-relevant chart (detailed breakdowns) and a user-relevant chart (single category score - priority)
      * Are the detailed breakdowns just covered by rigorous github issue use and appropriate labeling?

**Comment by sptramer** [comment]
Important downstream consequences of accepting this change:

* We'll need to update the source code for the feature grid to accept docs information.
* We'll need to update the instructions on how to use the feature grid.
* Should be future-proofed in terms of API reference generation so that we can link to red/yellow/green status dashboards for coverage.

**Comment by tonybalandiuk** [comment]
I think this information is useful in a table form, but 
1) it will require maintenance 
2) this information seems like it would be very useful at the top of each documentation page so someone using the actual documentation the completeness of it immediately (as opposed to having to know that this table exists). 

I'm wondering if there's a way to have this information at the top of each docs page, and then somehow run a script to aggregate it into this table. Then both use cases would be fulfilled.

**Comment by FiniteStateGit** [comment]
Closing proposal, feedback has been incorporated into RFC https://github.com/o3de/sig-docs-community/issues/64.
