### ISSUE TITLE
SIG-Docs-Community Election | Nominations 18 Aug - 29 Aug | Elections 31 Aug - 14 Sep

### ISSUE THREAD

**Issue by willihay** [o3de/sig-docs-community#57]
Hello all sig-docs-community:

For the first year of O3DE, @sptramer and @FiniteStateGit have served as the chairpersons of the Documentation & Community Special Interest Group. Now it's time for our second election season, leading into a 6-month term, which is shorter than the original sig-docs-community term length. We think that electing new representatives at this time in the leadup to the 22.10 release and closing of the year of 2022 will help us grow the SIG and better understand our users and community. Due to the expertise of the chairs and SIG members during the first year of O3DE, we have focused very heavily on documentation, and encourage the nomination of persons who are more focused on building our community.

The following things have changed since our last election:

* Terms are now officially 6 months, meaning our next election will be held in mid-March of 2023. Chairpersons may relinquish their chairship at any point and for any reason, but nominees should try and commit to their full term.
* Nominees are no longer required to be reviewers or maintainers, but reviewer/maintainer status is something nominees should highlight.
* Nominees should have at least some familiarity with open source, and one of either technical writing or community management/building.
* Nominees should provide a statement regarding their candidacy and what they see as important for the SIG to handle over the next 6-12 months. It's OK for a chair to set direction to continue after their term!
* Chairs are not required to provide on-call coverage of any sort.

## The chair / co-chair roles

The chair and co-chair serve equivalent roles in the governance of the SIG and are only differentiated by title in that the highest vote-getter is the chair and the second-highest is the co-chair. The chair and co-chair are expected to govern together in an effective way and split their responsibilities to make sure that the SIG operates smoothly and has the availability of a chairperson at any time.

Unless **distinctly required**, the term "chairperson" refers to either/both of the chair and co-chair. If a chair or co-chair is required to perform a specific responsibility for the SIG they will always be addressed by their official role title.

Chairs are not required to provide "on-call" support of any kind as part of their chairship. The O3D Foundation is responsible for addressing any high-severity issues related to documentation or community which would impact the immediate operation of the O3DE project or may result in legal liability of the O3D Foundation.

### Responsibilities

* Schedule and proctor regular SIG meetings on a cadence to be determined by the SIG.
* Planning and strategy for documentation and community building for O3DE.
* Serve as a source of authority (and ideally wisdom) with regards to O3DE documentation. Chairpersons are the ultimate arbiters of many documentation standards, processes, and practices.
* Act as representatives of the community, and provide advice to other SIGs, the Technical Steering Committee (TSC), and the Foundation on community building and management.
* Coordinate with partners and the Linux Foundation and Marketing Committee regarding official community events.
* Regularly participate in O3DE discussion channels such as our mailing lists, GitHub discussions, and Discord.

### Nomination requirements

Nominees must be an active contributor to Open 3D Engine in some fashion. Nominees should include any information on their work in O3DE (whether that is actively participating in Discord/forums/email, producing code submissions, producing docs submissions, or providing external tutorials or resources).

If you are nominated by somebody other than yourself, you're encouraged to provide your own statement (however brief). If you would like to decline a nomination, please do so on this issue before the nomination deadline.

### How to nominate

Nominations will be accepted beginning with the date of posting of this issue, until 2022-08-29 12:00PM PT.
Nominate somebody (including yourself) by responding to this issue with:

* A statement that the nominee should be nominated for a chair position in the Documentation & Community SIG.
* **If you are nominating somebody else:** Explain why you're doing so, provide some examples of their relevant contributions, and make sure that they are @-ed by their GitHub alias so they receive a notification and can respond.
* **If you are nominating yourself:** Provide a brief statement on your reasons for running for chairperson, and any information you think is useful about what you see as an ideal direction for O3DE with regards to documentation or community.
* The name under which the nominee should be addressed. Nominees are allowed to contact the election proctor to have this name changed.
* The GitHub username of the nominee. (Self-nominations need not include this; it's on your post.)
* Nominee's Discord username. Chairpersons must be active in the O3DE Discord if elected.

By accepting a nomination you acknowledge that you believe you can faithfully execute the role required of a chairperson for sig-docs-community for the next 6 months. Chairpersons may relinquish their chairship at any time and for any reason.

If only one nomination is received, nominations will remain open for an additional 2 weeks.

### Election process 

In the case where there are 2 candidates at the end of the nomination period, if they agree on chair and co-chair, no vote will be needed.

Otherwise, the election for chairpersons of sig-docs-community will occur one week after the nominations period closes.

Voting will be performed through an online mechanism TBD, starting 2 days after nominations are closed. The election voting will last for 2 weeks, tentatively scheduled for 2022-08-31 12:00PM PT until 2022-09-14 12:00PM PT.

Election results will be announced on or before 2022-09-15.

The elected chairpersons will begin serving their term at the start of the first sig-docs-community meeting following the end of the election, during which the handoff will occur.

**Comment by sptramer** [comment]
To jump in right away, I am going to decline both running again and any nominations for a chair position for this term. While I was happy to help ramp up the project and get some of the processes in place for us to start working collaboratively and getting docs published, it's time for a break.

**Comment by aFinchy** [comment]
I nominate @FiniteStateGit for the role of Chair for the Docs SIG.

**Comment by chanmosq** [comment]
I nominate myself as chair or co-chair of Documentation and Community SIG for this upcoming term. 

As a reviewer and maintainer, I've made and reviewed countless pull requests and addressed issues to help shape the O3DE Documentation. With my background in technical writing, I can continue to provide a perspective to support documentation. As an active member and with my connections in the O3DF community, I can also support and help grow the community side of the SIG.

**Comment by chanmosq** [comment]
I nominate @aFinchy as chair or co-chair of Documentation and Community SIG for this upcoming term. 

Amy has been an active manager of the O3DF Discord community and has industry experience as a community manager. As an example, recently Amy has been leading the effort around blogs and other community learning events. Therefore, I think Amy can provide a perspective towards community, as well as support for O3DE Documentation and where the two cross.

**Comment by aFinchy** [comment]
Thanks for nominating me @chanmosq! I understand the responsibilities and requirements of the role and promise to faithfully fulfill them and follow all contributor requirements for O3DE.

**Comment by aFinchy** [comment]
I second the nomination of @chanmosq for the role of Chair for the Docs & Community SIG.

**Comment by FiniteStateGit** [comment]
I decline nomination for chair of sig-docs-community in support of the candidacies of @aFinchy and @chanmosq.

**Comment by willihay** [comment]
Nominations are now closed. We have two nominations for two positions. Congratulations to @chanmosq and @aFinchy, our new co-chairs!

**Comment by willihay** [comment]
New chairs start today. Closing issue.

**Comment by amzn-changml** [comment]
I've granted @chanmosq and @aFinchy two new teams: 

https://github.com/orgs/o3de/teams/sig-docs-community-reviewers/members 
https://github.com/orgs/o3de/teams/sig-docs-community-maintainers/members 

These teams have write and maintain access respectively to the repo https://github.com/o3de/community. In addition, they are team maintainers and can invite existing members as reviewers and maintainers

**Comment by aFinchy** [comment]
> I've granted @chanmosq and @aFinchy two new teams:
> 
> https://github.com/orgs/o3de/teams/sig-docs-community-reviewers/members https://github.com/orgs/o3de/teams/sig-docs-community-maintainers/members
> 
> These teams have write and maintain access respectively to the repo https://github.com/o3de/community. In addition, they are team maintainers and can invite existing members as reviewers and maintainers

Thanks for the update and adding those, :)
