### ISSUE TITLE
RFC: SIG Charter Review

### ISSUE THREAD

**Issue by sptramer** [o3de/sig-docs-community#8]
## Summary

This issue is for a formal review of the SIG Charter after discussion in the 21-08-27 SIG meeting. There is an open pull request, PR 
#6, which will be used to collect changes that result from this discussion. Please review the [D&C SIG Charter](https://github.com/o3de/sig-docs-community/blob/main/governance/charter.md) and provide the feedback on this issue.

### Providing feedback

* If you're providing general feedback on the SIG rather than a specific line or element in the charter, provide as much information and context as you need to.
* If you're responding to specific text or items in the SIG charter itself, please include the context for the part of the document you're referring to in a quote (markdown `>` leader).

**Comment by FiniteStateGit** [comment]
Should the O3DE wiki be added to the scope of this SIG?

**Comment by sptramer** [comment]
**Closes for comment 9/30/2021**

**Comment by sptramer** [comment]
> 
> 
> Should the O3DE wiki be added to the scope of this SIG?

I don't think so, the wiki is meant for engineering notes and used how the engineers want. It's subject to all the CoC restrictions so I don't think we need to officially control/monitor it.
