### ISSUE TITLE
Create Roadmap View

### ISSUE THREAD

**Issue by vincent6767** [o3de/sig-docs-community#97]
Hi! SIG release is working to help the O3DE community to get visibility of the O3DE roadmap. Full context can be read here: https://github.com/o3de/sig-release/issues/79. 

In order to achieve that goal, we need your help to create the roadmap for your SIG by **February 6th, 2023**, and start giving brief updates about the roadmap items at the **Joint TSC meeting on February 28th, 2023**. Instruction to create the roadmap view can be read in the RFC section "Roadmap Review in TSC monthly meeting".

Let me know if you have any concerns with the dates or any questions about the ask!

**Comment by vincent6767** [comment]
Hi @chanmosq @aFinchy , a friendly reminder to help review by next week as we want every SIG to have a roadmap according to the RFC attached above by February 10th, 2023.

**Comment by vincent6767** [comment]
Thanks, @chanmosq One question. Is it intended there are no issues with the kind/roadmap at this moment?

**Comment by chanmosq** [comment]
Yes that's correct. We're working on roadmap items at the moment

**Comment by vincent6767** [comment]
Thanks for clarifying!
